### PR TITLE
AB#723 Add support for yml manifest and provide manifest templates

### PR DESCRIPTION
**Pull request by daniel-weisse**

### CODE REVIEW

**Review by m1ghtym0 — COMMENTED** [review]
Please add a unit test for loading both file types

**Review by m1ghtym0 — COMMENTED** [review]
Please add support to output in yaml as well.
We can use the `-o` parameter for this and output the result to stdout directly.

**Review by m1ghtym0 — COMMENTED** [review]
I just noticed that we actually were missing something here.
The Client API `GET /manifest` actually does not return the whole manifest.
Only the manifest's signature is returned.
So it will get quite confusing if we output something called `manifest.json` either as json or yaml.
Instead we should only print the manifest signature to stdout.
Something like: `Manifest signature: 0x8080384028`
The CLI should output this signature when calling manifest set (it's just the sha256sum in the end).
We should also add a command `manifest signature` that prints the signature of a given yaml or json file

**Review by m1ghtym0 — APPROVED** [review]
lgtm:-)
@thomasten do you think it's ok that we calculate the signature locally?
imo it's just sha256 so we're not doing any magic here.

**Comment by thomasten** [comment]
> @thomasten do you think it's ok that we calculate the signature locally?
> imo it's just sha256 so we're not doing any magic here.

I think it does not differ from the current workflow `sha256sum manifest.json`

**Pull request merged**
