### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by flxflx**
Update logo and remove obsolete sentence from README.

### CODE REVIEW

**Review by thomasten — CHANGES_REQUESTED** [review]
the text isn't rendered correctly if you don't have the font installed

**Comment by laralaske** [comment]
Updated shade of green marblerun logo: https://edgelesscompute.sharepoint.com/:u:/s/Docs/EergL3nuesxFnRXt8UktHX8BbSWrcCWmqU-2Bn5KcgM4ng?e=g1xean

**Comment by flxflx** [comment]
Ok, transformed the text to a vector path.

**Review by thomasten — APPROVED** [review]
Now looks good on my machine. Before you merge this, please compare
https://github.com/edgelesssys/marblerun?tab=readme-ov-file#marblerun
and
https://github.com/edgelesssys/marblerun/tree/logo-update?tab=readme-ov-file#marblerun
to check if the change in size is what you want.

**Comment by laralaske** [comment]
Here's a smaller svg so that it doesn't become so big in the readme: https://edgelesscompute.sharepoint.com/:u:/r/sites/Docs/Shared%20Documents/Marketing/Corporate%20Design/Products/MarbleRun/MarbleRun%20logo%20with%20text%202024%20small.svg?csf=1&web=1&e=yl0wFM

**Pull request merged**
