### PR TITLE
add docs to project repo

### PR DESCRIPTION
**Pull request by thomasten**
I couldn't get the swagger page (https://docs.edgeless.systems/marblerun/#/reference/coordinator) to work. I omitted it for now.

### CODE REVIEW

**Review by m1ghtym0 — COMMENTED** [review]
Here is the preview: https://deploy-preview-83--edgeless-docs.netlify.app/marblerun
We need to point the OpenAPI workflow to this repo and the docs folder.
I can do that once all the fixes are done.

**Comment by m1ghtym0** [comment]
I've added a plugin to render the OpenAPI spec and adjusted the workflows. Please have a look at the result and let me know what you think.

**Review by m1ghtym0 — APPROVED** [review]

**Comment by thomasten** [comment]
Can you review the two fixup commits? If everything is ok now, I'll clean up history and merge.
Regarding the change in coordinator.md: I copied that from the swagger page, so this would now be shown twice. So I reverted this.

**Review by m1ghtym0 — APPROVED** [review]
Oh dear, thanks for noticing!

**Pull request merged**
